[package]
name = "suitware-synthesis"
version = "0.1.0"
edition = "2021"

[dependencies]
twang = "0.7"
fon = "0.5"

color-eyre = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"

pasts = "0.7.0"
futures = "0.3.19"
wavy = "0.9"
